In [1]:
# Imports
import os
import polars as pl
import duckdb
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import re

# # Opciones de visualización
# %matplotlib inline
# plt.rcParams['figure.figsize'] = (10,5)

In [2]:
path = '../results/championship/'
files = os.listdir(path)
regex = re.compile(r'(\d+_\d+)_(.*).parquet')

In [3]:
dict_edition_phase = {}
for file in files:
    match = regex.match(file)
    if match:
        edition = match.group(1)
        phase = match.group(2)
        df = pl.read_parquet(f'{path}{file}')
        if edition not in dict_edition_phase:
            dict_edition_phase[edition] = {phase: df}
        else:
            dict_edition_phase[edition][phase] = df

        print(f'Edition: {edition}, Phase: {phase}')

Edition: 20251207_110916, Phase: first_phase
Edition: 20251207_110916, Phase: second_phase
Edition: 20251207_110916, Phase: third_phase
Edition: 20251208_114259, Phase: first_phase
Edition: 20251208_114259, Phase: second_phase
Edition: 20251208_114259, Phase: third_phase
Edition: 20251208_114346, Phase: first_phase
Edition: 20251208_114346, Phase: second_phase
Edition: 20251208_114346, Phase: third_phase
Edition: 20251208_114408, Phase: first_phase
Edition: 20251208_114408, Phase: second_phase
Edition: 20251208_114408, Phase: third_phase
Edition: 20251208_114426, Phase: first_phase
Edition: 20251208_114426, Phase: second_phase
Edition: 20251208_114426, Phase: third_phase
Edition: 20251208_114444, Phase: first_phase
Edition: 20251208_114444, Phase: second_phase
Edition: 20251208_114444, Phase: third_phase
Edition: 20251208_114539, Phase: first_phase
Edition: 20251208_114539, Phase: second_phase
Edition: 20251208_114539, Phase: third_phase

In [4]:
edition = "20251207_110916"
sample_first = dict_edition_phase.get(edition).get("first_phase")
sample_second = dict_edition_phase.get(edition).get("second_phase")
sample_third = dict_edition_phase.get(edition).get("third_phase")

# Samples

In [19]:
sample_first

shape: (182, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ game_numb ┆ repetitio ┆ num_round ┆ p1_name   ┆ … ┆ p1_payoff ┆ p2_payoff ┆ mean_scor ┆ mean_sco │
│ er        ┆ n         ┆ s         ┆ ---       ┆   ┆ ---       ┆ ---       ┆ e_p1      ┆ re_p2    │
│ ---       ┆ ---       ┆ ---       ┆ str       ┆   ┆ list[i64] ┆ list[i64] ┆ ---       ┆ ---      │
│ i64       ┆ i64       ┆ i64       ┆           ┆   ┆           ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 1         ┆ 1         ┆ Adaptive  ┆ … ┆ [2]       ┆ [2]       ┆ 2.0       ┆ 2.0      │
│           ┆           ┆           ┆ Pavlov    ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2         ┆ 35        ┆ Adaptive  ┆ … ┆ [2, 2, …  ┆ [2, 2, …  ┆ 1.971429  ┆ 2.142857 │
│           ┆           ┆           ┆ Pavlov    ┆   ┆ 2]        ┆ 2]        ┆           ┆          │
│ 3         ┆ 1         ┆ 100       ┆ Adaptive  ┆ … ┆ [0, 0, …  ┆ [0, 0, …  ┆ 1.62      ┆ 1.29     │
│           ┆           ┆           ┆ Pavlov    ┆   ┆ 3]        ┆ 2]        ┆           ┆          │
│ 4         ┆ 2         ┆ 10        ┆ Adaptive  ┆ … ┆ [0, 0, …  ┆ [0, 0, …  ┆ 0.0       ┆ 0.0      │
│           ┆           ┆           ┆ Pavlov    ┆   ┆ 0]        ┆ 0]        ┆           ┆          │
│ 5         ┆ 1         ┆ 49        ┆ Adaptive  ┆ … ┆ [2, 2, …  ┆ [2, 2, …  ┆ 2.0       ┆ 2.020408 │
│           ┆           ┆           ┆ Pavlov    ┆   ┆ 2]        ┆ 2]        ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 178       ┆ 2         ┆ 49        ┆ Random 2  ┆ … ┆ [2, 3, …  ┆ [3, 2, …  ┆ 1.857143  ┆ 1.755102 │
│           ┆           ┆           ┆ or 3      ┆   ┆ 3]        ┆ 2]        ┆           ┆          │
│ 179       ┆ 1         ┆ 22        ┆ Random 2  ┆ … ┆ [3, 0, …  ┆ [2, 0, …  ┆ 1.5       ┆ 1.5      │
│           ┆           ┆           ┆ or 3      ┆   ┆ 2]        ┆ 3]        ┆           ┆          │
│ 180       ┆ 2         ┆ 48        ┆ Random 2  ┆ … ┆ [3, 0, …  ┆ [2, 0, …  ┆ 1.5       ┆ 1.75     │
│           ┆           ┆           ┆ or 3      ┆   ┆ 0]        ┆ 0]        ┆           ┆          │
│ 181       ┆ 1         ┆ 35        ┆ Weighted  ┆ … ┆ [2, 2, …  ┆ [2, 3, …  ┆ 1.857143  ┆ 2.628571 │
│           ┆           ┆           ┆ Random 2, ┆   ┆ 2]        ┆ 2]        ┆           ┆          │
│           ┆           ┆           ┆ 3, or 4   ┆   ┆           ┆           ┆           ┆          │
│ 182       ┆ 2         ┆ 30        ┆ Weighted  ┆ … ┆ [3, 2, …  ┆ [2, 3, …  ┆ 1.7       ┆ 2.166667 │
│           ┆           ┆           ┆ Random 2, ┆   ┆ 2]        ┆ 3]        ┆           ┆          │
│           ┆           ┆           ┆ 3, or 4   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [22]:
duckdb.query("""
SELECT game_number, p1_name, p2_name, mean_score_p1, mean_score_p2, list_avg(p1_payoff)
FROM sample_first
""")

┌─────────────┬────────────────────────────┬────────────────────────────┬────────────────────┬────────────────────┬─────────────────────┐
│ game_number │          p1_name           │          p2_name           │   mean_score_p1    │   mean_score_p2    │ list_avg(p1_payoff) │
│    int64    │          varchar           │          varchar           │       double       │       double       │       double        │
├─────────────┼────────────────────────────┼────────────────────────────┼────────────────────┼────────────────────┼─────────────────────┤
│           1 │ Adaptive Pavlov            │ Agente Astuto              │                2.0 │                2.0 │                 2.0 │
│           2 │ Adaptive Pavlov            │ Agente Astuto              │ 1.9714285714285715 │  2.142857142857143 │  1.9714285714285715 │
│           3 │ Adaptive Pavlov            │ BinarySunset               │               1.62 │               1.29 │                1.62 │
│           4 │ Adaptive Pavlov            │ BinarySunset               │                0.0 │                0.0 │                 0.0 │
│           5 │ Adaptive Pavlov            │ Contrite TFT               │                2.0 │  2.020408163265306 │                 2.0 │
│           6 │ Adaptive Pavlov            │ Contrite TFT               │ 1.9285714285714286 │ 1.8928571428571428 │  1.9285714285714286 │
│           7 │ Adaptive Pavlov            │ CopyCat                    │  1.992537313432836 │                2.0 │   1.992537313432836 │
│           8 │ Adaptive Pavlov            │ CopyCat                    │            1.96875 │            1.96875 │             1.96875 │
│           9 │ Adaptive Pavlov            │ Detective Avanzado         │  1.934782608695652 │  2.858695652173913 │   1.934782608695652 │
│          10 │ Adaptive Pavlov            │ Detective Avanzado         │ 1.8955223880597014 │ 2.7611940298507465 │  1.8955223880597014 │
│           · │        ·                   │         ·                  │          ·         │          ·         │           ·         │
│           · │        ·                   │         ·                  │          ·         │          ·         │           ·         │
│           · │        ·                   │         ·                  │          ·         │          ·         │           ·         │
│         173 │ Permissive Tit for Tat     │ Weighted Random 2, 3, or 4 │ 2.0526315789473686 │  2.210526315789474 │  2.0526315789473686 │
│         174 │ Permissive Tit for Tat     │ Weighted Random 2, 3, or 4 │ 2.0441176470588234 │ 2.3455882352941178 │  2.0441176470588234 │
│         175 │ Permissive Tit for Tat     │ WSLS                       │ 1.8157894736842106 │  2.219298245614035 │  1.8157894736842106 │
│         176 │ Permissive Tit for Tat     │ WSLS                       │                3.0 │                2.0 │                 3.0 │
│         177 │ Random 2 or 3              │ Weighted Random 2, 3, or 4 │                2.0 │ 1.8596491228070176 │                 2.0 │
│         178 │ Random 2 or 3              │ Weighted Random 2, 3, or 4 │ 1.8571428571428572 │ 1.7551020408163265 │  1.8571428571428572 │
│         179 │ Random 2 or 3              │ WSLS                       │                1.5 │                1.5 │                 1.5 │
│         180 │ Random 2 or 3              │ WSLS                       │                1.5 │               1.75 │                 1.5 │
│         181 │ Weighted Random 2, 3, or 4 │ WSLS                       │ 1.8571428571428572 │ 2.6285714285714286 │  1.8571428571428572 │
│         182 │ Weighted Random 2, 3, or 4 │ WSLS                       │                1.7 │ 2.1666666666666665 │                 1.7 │
├─────────────┴────────────────────────────┴────────────────────────────┴────────────────────┴────────────────────┴─────────────────────┤
│ 182 rows (20 shown)                                                                                                         6 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

## Mayor media

Toneo y global

In [30]:
duckdb.query("""
SELECT p1_name as player_name, list_sum(p1_payoff) as player_score, num_rounds as players_rounds, player_score/players_rounds as mean , mean_score_p1    
FROM sample_first
""")

┌────────────────────────────┬──────────────┬────────────────┬────────────────────┬────────────────────┐
│        player_name         │ player_score │ players_rounds │        mean        │   mean_score_p1    │
│          varchar           │    int128    │     int64      │       double       │       double       │
├────────────────────────────┼──────────────┼────────────────┼────────────────────┼────────────────────┤
│ Adaptive Pavlov            │            2 │              1 │                2.0 │                2.0 │
│ Adaptive Pavlov            │           69 │             35 │ 1.9714285714285715 │ 1.9714285714285715 │
│ Adaptive Pavlov            │          162 │            100 │               1.62 │               1.62 │
│ Adaptive Pavlov            │            0 │             10 │                0.0 │                0.0 │
│ Adaptive Pavlov            │           98 │             49 │                2.0 │                2.0 │
│ Adaptive Pavlov            │          108 │             56 │ 1.9285714285714286 │ 1.9285714285714286 │
│ Adaptive Pavlov            │          534 │            268 │  1.992537313432836 │  1.992537313432836 │
│ Adaptive Pavlov            │           63 │             32 │            1.96875 │            1.96875 │
│ Adaptive Pavlov            │          178 │             92 │  1.934782608695652 │  1.934782608695652 │
│ Adaptive Pavlov            │          127 │             67 │ 1.8955223880597014 │ 1.8955223880597014 │
│        ·                   │            · │              · │          ·         │          ·         │
│        ·                   │            · │              · │          ·         │          ·         │
│        ·                   │            · │              · │          ·         │          ·         │
│ Permissive Tit for Tat     │           39 │             19 │ 2.0526315789473686 │ 2.0526315789473686 │
│ Permissive Tit for Tat     │          278 │            136 │ 2.0441176470588234 │ 2.0441176470588234 │
│ Permissive Tit for Tat     │          207 │            114 │ 1.8157894736842106 │ 1.8157894736842106 │
│ Permissive Tit for Tat     │            3 │              1 │                3.0 │                3.0 │
│ Random 2 or 3              │          114 │             57 │                2.0 │                2.0 │
│ Random 2 or 3              │           91 │             49 │ 1.8571428571428572 │ 1.8571428571428572 │
│ Random 2 or 3              │           33 │             22 │                1.5 │                1.5 │
│ Random 2 or 3              │           72 │             48 │                1.5 │                1.5 │
│ Weighted Random 2, 3, or 4 │           65 │             35 │ 1.8571428571428572 │ 1.8571428571428572 │
│ Weighted Random 2, 3, or 4 │           51 │             30 │                1.7 │                1.7 │
├────────────────────────────┴──────────────┴────────────────┴────────────────────┴────────────────────┤
│ 182 rows (20 shown)                                                                        5 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [67]:
# Primer torneo
duckdb.query("""
SELECT player_name, SUM(player_score) as total_score, SUM(num_rounds) as total_rounds, total_score/total_rounds as Average
FROM (
    SELECT p1_name as player_name, list_sum(p1_payoff) as player_score, num_rounds
    FROM sample_first
    UNION ALL
    SELECT p2_name as player_name, list_sum(p2_payoff) as player_score, num_rounds
    FROM sample_first
    )
GROUP BY player_name
ORDER BY Average DESC
""")

┌────────────────────────────┬─────────────┬──────────────┬────────────────────┐
│        player_name         │ total_score │ total_rounds │      Average       │
│          varchar           │   int128    │    int128    │       double       │
├────────────────────────────┼─────────────┼──────────────┼────────────────────┤
│ Adaptive Pavlov            │        4159 │         2124 │ 1.9580979284369116 │
│ Hat Tricker                │        5123 │         2706 │ 1.8932002956393201 │
│ Weighted Random 2, 3, or 4 │        2844 │         1528 │  1.861256544502618 │
│ Contrite TFT               │        4981 │         2766 │ 1.8007953723788865 │
│ Permissive Tit for Tat     │        4935 │         2950 │ 1.6728813559322033 │
│ WSLS                       │        4406 │         2681 │ 1.6434166355837374 │
│ Random 2 or 3              │        4901 │         3007 │ 1.6298636514798803 │
│ Agente Astuto              │        4213 │         2596 │ 1.6228813559322033 │
│ Generous TFT               │        4875 │         3217 │  1.515387006527821 │
│ BinarySunset               │        4683 │         3133 │ 1.4947334822853495 │
│ CopyCat                    │        5188 │         3618 │ 1.4339414040906577 │
│ Detective Avanzado         │        2557 │         1888 │ 1.3543432203389831 │
│ Deterministic Simpletron   │        3496 │         3115 │    1.1223113964687 │
│ Grim Trigger               │        2804 │         2961 │ 0.9469773725092874 │
├────────────────────────────┴─────────────┴──────────────┴────────────────────┤
│ 14 rows                                                            4 columns │
└──────────────────────────────────────────────────────────────────────────────┘

In [68]:
# Total
duckdb.query("""
SELECT player_name, SUM(player_score) as total_score, SUM(num_rounds) as total_rounds, total_score/total_rounds as Average
FROM (
    SELECT p1_name as player_name, list_sum(p1_payoff) as player_score, num_rounds
    FROM sample_first
    UNION ALL
    SELECT p2_name as player_name, list_sum(p2_payoff) as player_score, num_rounds
    FROM sample_first
    UNION ALL
    SELECT p1_name as player_name, list_sum(p1_payoff) as player_score, num_rounds
    FROM sample_second
    UNION ALL
    SELECT p2_name as player_name, list_sum(p2_payoff) as player_score, num_rounds
    FROM sample_second
    UNION ALL
    SELECT p1_name as player_name, list_sum(p1_payoff) as player_score, num_rounds
    FROM sample_third
    UNION ALL
    SELECT p2_name as player_name, list_sum(p2_payoff) as player_score, num_rounds
    FROM sample_third
    )
GROUP BY player_name
ORDER BY Average DESC
""")

┌────────────────────────────┬─────────────┬──────────────┬──────────────────────┐
│        player_name         │ total_score │ total_rounds │       Average        │
│          varchar           │   int128    │    int128    │        double        │
├────────────────────────────┼─────────────┼──────────────┼──────────────────────┤
│ Adaptive Pavlov            │      123822 │        63112 │   1.9619406768918748 │
│ Focal 5                    │       67812 │        35228 │    1.924946065629613 │
│ Castigador Infernal        │       67183 │        35823 │   1.8754152360215504 │
│ Hat Tricker                │      112528 │        61831 │   1.8199285148226618 │
│ Weighted Random 2, 3, or 4 │      112692 │        62422 │   1.8053250456569798 │
│ Contrite TFT               │      105426 │        62589 │   1.6844173896371566 │
│ Random 2 or 3              │      111819 │        67561 │   1.6550820739775907 │
│ WSLS                       │      104656 │        63246 │   1.6547449641084022 │
│ Generous TFT               │       91543 │        60244 │   1.5195372153243476 │
│ Permissive Tit for Tat     │       93415 │        62106 │   1.5041219849933984 │
│ Agente Astuto              │       94207 │        64008 │   1.4718003999500062 │
│ CopyCat                    │       94861 │        64453 │   1.4717856422509425 │
│ BinarySunset               │       65971 │        45719 │   1.4429668190467857 │
│ Tit for Tat                │       52177 │        36256 │   1.4391273168578993 │
│ Deterministic Simpletron   │       78787 │        59784 │    1.317860966144788 │
│ Always 3                   │       44149 │        34140 │   1.2931751611013473 │
│ Detective Avanzado         │       76077 │        60176 │    1.264241558096251 │
│ Grim Trigger               │       77369 │        61961 │   1.2486725520892175 │
│ Uniform Random             │       14529 │        19046 │   0.7628373411739998 │
│ Always 0                   │          40 │         4129 │ 0.009687575684185032 │
├────────────────────────────┴─────────────┴──────────────┴──────────────────────┤
│ 20 rows                                                              4 columns │
└────────────────────────────────────────────────────────────────────────────────┘

## Nemesis

In [44]:
duckdb.query("""
    SELECT 
        p1_name,
        p2_name,
        list_sum(p1_payoff) AS p1_points,
        list_sum(p2_payoff) AS p2_points,
        CASE 
            WHEN list_sum(p1_payoff) > list_sum(p2_payoff) THEN p1_name
            WHEN list_sum(p2_payoff) > list_sum(p1_payoff) THEN p2_name
            ELSE NULL
        END AS winner,
        CASE 
            WHEN list_sum(p1_payoff) < list_sum(p2_payoff) THEN p1_name
            WHEN list_sum(p2_payoff) < list_sum(p1_payoff) THEN p2_name
            ELSE NULL
        END AS Looser,
        list_sum(p1_payoff) = list_sum(p2_payoff) AS is_draw
    FROM sample_first
""")

┌────────────────────────────┬────────────────────────────┬───────────┬───────────┬────────────────────────────┬────────────────────────────┬─────────┐
│          p1_name           │          p2_name           │ p1_points │ p2_points │           winner           │           Looser           │ is_draw │
│          varchar           │          varchar           │  int128   │  int128   │          varchar           │          varchar           │ boolean │
├────────────────────────────┼────────────────────────────┼───────────┼───────────┼────────────────────────────┼────────────────────────────┼─────────┤
│ Adaptive Pavlov            │ Agente Astuto              │         2 │         2 │ NULL                       │ NULL                       │ true    │
│ Adaptive Pavlov            │ Agente Astuto              │        69 │        75 │ Agente Astuto              │ Adaptive Pavlov            │ false   │
│ Adaptive Pavlov            │ BinarySunset               │       162 │       129 │ Adaptive Pavlov            │ BinarySunset               │ false   │
│ Adaptive Pavlov            │ BinarySunset               │         0 │         0 │ NULL                       │ NULL                       │ true    │
│ Adaptive Pavlov            │ Contrite TFT               │        98 │        99 │ Contrite TFT               │ Adaptive Pavlov            │ false   │
│ Adaptive Pavlov            │ Contrite TFT               │       108 │       106 │ Adaptive Pavlov            │ Contrite TFT               │ false   │
│ Adaptive Pavlov            │ CopyCat                    │       534 │       536 │ CopyCat                    │ Adaptive Pavlov            │ false   │
│ Adaptive Pavlov            │ CopyCat                    │        63 │        63 │ NULL                       │ NULL                       │ true    │
│ Adaptive Pavlov            │ Detective Avanzado         │       178 │       263 │ Detective Avanzado         │ Adaptive Pavlov            │ false   │
│ Adaptive Pavlov            │ Detective Avanzado         │       127 │       185 │ Detective Avanzado         │ Adaptive Pavlov            │ false   │
│        ·                   │         ·                  │         · │         · │         ·                  │        ·                   │   ·     │
│        ·                   │         ·                  │         · │         · │         ·                  │        ·                   │   ·     │
│        ·                   │         ·                  │         · │         · │         ·                  │        ·                   │   ·     │
│ Permissive Tit for Tat     │ Weighted Random 2, 3, or 4 │        39 │        42 │ Weighted Random 2, 3, or 4 │ Permissive Tit for Tat     │ false   │
│ Permissive Tit for Tat     │ Weighted Random 2, 3, or 4 │       278 │       319 │ Weighted Random 2, 3, or 4 │ Permissive Tit for Tat     │ false   │
│ Permissive Tit for Tat     │ WSLS                       │       207 │       253 │ WSLS                       │ Permissive Tit for Tat     │ false   │
│ Permissive Tit for Tat     │ WSLS                       │         3 │         2 │ Permissive Tit for Tat     │ WSLS                       │ false   │
│ Random 2 or 3              │ Weighted Random 2, 3, or 4 │       114 │       106 │ Random 2 or 3              │ Weighted Random 2, 3, or 4 │ false   │
│ Random 2 or 3              │ Weighted Random 2, 3, or 4 │        91 │        86 │ Random 2 or 3              │ Weighted Random 2, 3, or 4 │ false   │
│ Random 2 or 3              │ WSLS                       │        33 │        33 │ NULL                       │ NULL                       │ true    │
│ Random 2 or 3              │ WSLS                       │        72 │        84 │ WSLS                       │ Random 2 or 3              │ false   │
│ Weighted Random 2, 3, or 4 │ WSLS                       │        65 │        92 │ WSLS                       │ Weighted Random 2, 3, or 4 │ false   │
│ Weighted Random 2, 3, or 4 │ WSLS                       │        51 │        65 │ WSLS                       │ Weighted Random 2, 3, or 4 │ false   │
├────────────────────────────┴────────────────────────────┴───────────┴───────────┴────────────────────────────┴────────────────────────────┴─────────┤
│ 182 rows (20 shown)                                                                                                                       7 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [49]:
player = "Adaptive Pavlov"

In [52]:
duckdb.query(f"""
    SELECT Looser, Winner, count(*) as perdidos
    FROM (
        SELECT 
            p1_name,
            p2_name,
            list_sum(p1_payoff) AS p1_points,
            list_sum(p2_payoff) AS p2_points,
            CASE 
                WHEN list_sum(p1_payoff) > list_sum(p2_payoff) THEN p1_name
                WHEN list_sum(p2_payoff) > list_sum(p1_payoff) THEN p2_name
                ELSE NULL
            END AS winner,
            CASE 
                WHEN list_sum(p1_payoff) < list_sum(p2_payoff) THEN p1_name
                WHEN list_sum(p2_payoff) < list_sum(p1_payoff) THEN p2_name
                ELSE NULL
            END AS Looser,
            list_sum(p1_payoff) = list_sum(p2_payoff) AS is_draw
        FROM sample_first
    )
    WHERE Looser = '{player}'
    GROUP BY Looser, Winner
    ORDER BY perdidos DESC
    """)

┌─────────────────┬────────────────────────────┬──────────┐
│     Looser      │           winner           │ perdidos │
│     varchar     │          varchar           │  int64   │
├─────────────────┼────────────────────────────┼──────────┤
│ Adaptive Pavlov │ WSLS                       │        2 │
│ Adaptive Pavlov │ Detective Avanzado         │        2 │
│ Adaptive Pavlov │ Grim Trigger               │        2 │
│ Adaptive Pavlov │ Random 2 or 3              │        2 │
│ Adaptive Pavlov │ Hat Tricker                │        2 │
│ Adaptive Pavlov │ Generous TFT               │        1 │
│ Adaptive Pavlov │ Weighted Random 2, 3, or 4 │        1 │
│ Adaptive Pavlov │ Contrite TFT               │        1 │
│ Adaptive Pavlov │ CopyCat                    │        1 │
│ Adaptive Pavlov │ Agente Astuto              │        1 │
│ Adaptive Pavlov │ Permissive Tit for Tat     │        1 │
├─────────────────┴────────────────────────────┴──────────┤
│ 11 rows                                       3 columns │
└─────────────────────────────────────────────────────────┘

In [53]:
duckdb.query(f"""
    SELECT Looser, Winner, count(*) as perdidos
    FROM (
        SELECT 
            p1_name,
            p2_name,
            list_sum(p1_payoff) AS p1_points,
            list_sum(p2_payoff) AS p2_points,
            CASE 
                WHEN list_sum(p1_payoff) > list_sum(p2_payoff) THEN p1_name
                WHEN list_sum(p2_payoff) > list_sum(p1_payoff) THEN p2_name
                ELSE NULL
            END AS winner,
            CASE 
                WHEN list_sum(p1_payoff) < list_sum(p2_payoff) THEN p1_name
                WHEN list_sum(p2_payoff) < list_sum(p1_payoff) THEN p2_name
                ELSE NULL
            END AS Looser,
            list_sum(p1_payoff) = list_sum(p2_payoff) AS is_draw
        FROM sample_first
        UNION ALL
        SELECT 
            p1_name,
            p2_name,
            list_sum(p1_payoff) AS p1_points,
            list_sum(p2_payoff) AS p2_points,
            CASE 
                WHEN list_sum(p1_payoff) > list_sum(p2_payoff) THEN p1_name
                WHEN list_sum(p2_payoff) > list_sum(p1_payoff) THEN p2_name
                ELSE NULL
            END AS winner,
            CASE 
                WHEN list_sum(p1_payoff) < list_sum(p2_payoff) THEN p1_name
                WHEN list_sum(p2_payoff) < list_sum(p1_payoff) THEN p2_name
                ELSE NULL
            END AS Looser,
            list_sum(p1_payoff) = list_sum(p2_payoff) AS is_draw
        FROM sample_second
        UNION ALL
        SELECT 
            p1_name,
            p2_name,
            list_sum(p1_payoff) AS p1_points,
            list_sum(p2_payoff) AS p2_points,
            CASE 
                WHEN list_sum(p1_payoff) > list_sum(p2_payoff) THEN p1_name
                WHEN list_sum(p2_payoff) > list_sum(p1_payoff) THEN p2_name
                ELSE NULL
            END AS winner,
            CASE 
                WHEN list_sum(p1_payoff) < list_sum(p2_payoff) THEN p1_name
                WHEN list_sum(p2_payoff) < list_sum(p1_payoff) THEN p2_name
                ELSE NULL
            END AS Looser,
            list_sum(p1_payoff) = list_sum(p2_payoff) AS is_draw
        FROM sample_third
    )
    WHERE Looser = '{player}'
    GROUP BY Looser, Winner
    ORDER BY perdidos DESC
    """)

┌─────────────────┬────────────────────────────┬──────────┐
│     Looser      │           winner           │ perdidos │
│     varchar     │          varchar           │  int64   │
├─────────────────┼────────────────────────────┼──────────┤
│ Adaptive Pavlov │ Detective Avanzado         │       42 │
│ Adaptive Pavlov │ Grim Trigger               │       42 │
│ Adaptive Pavlov │ Random 2 or 3              │       42 │
│ Adaptive Pavlov │ WSLS                       │       42 │
│ Adaptive Pavlov │ Hat Tricker                │       42 │
│ Adaptive Pavlov │ Weighted Random 2, 3, or 4 │       41 │
│ Adaptive Pavlov │ Agente Astuto              │       40 │
│ Adaptive Pavlov │ Deterministic Simpletron   │       33 │
│ Adaptive Pavlov │ Permissive Tit for Tat     │       24 │
│ Adaptive Pavlov │ CopyCat                    │       21 │
│ Adaptive Pavlov │ Focal 5                    │       20 │
│ Adaptive Pavlov │ Always 3                   │       20 │
│ Adaptive Pavlov │ Castigador Infernal        │       19 │
│ Adaptive Pavlov │ Contrite TFT               │       19 │
│ Adaptive Pavlov │ Generous TFT               │       17 │
│ Adaptive Pavlov │ Tit for Tat                │       14 │
├─────────────────┴────────────────────────────┴──────────┤
│ 16 rows                                       3 columns │
└─────────────────────────────────────────────────────────┘

In [54]:
duckdb.query(f"""
    SELECT Looser, Winner, count(*) as perdidos
    FROM (
        SELECT 
            p1_name,
            p2_name,
            list_sum(p1_payoff) AS p1_points,
            list_sum(p2_payoff) AS p2_points,
            CASE 
                WHEN list_sum(p1_payoff) > list_sum(p2_payoff) THEN p1_name
                WHEN list_sum(p2_payoff) > list_sum(p1_payoff) THEN p2_name
                ELSE NULL
            END AS winner,
            CASE 
                WHEN list_sum(p1_payoff) < list_sum(p2_payoff) THEN p1_name
                WHEN list_sum(p2_payoff) < list_sum(p1_payoff) THEN p2_name
                ELSE NULL
            END AS Looser,
            list_sum(p1_payoff) = list_sum(p2_payoff) AS is_draw
        FROM sample_first
        UNION ALL
        SELECT 
            p1_name,
            p2_name,
            list_sum(p1_payoff) AS p1_points,
            list_sum(p2_payoff) AS p2_points,
            CASE 
                WHEN list_sum(p1_payoff) > list_sum(p2_payoff) THEN p1_name
                WHEN list_sum(p2_payoff) > list_sum(p1_payoff) THEN p2_name
                ELSE NULL
            END AS winner,
            CASE 
                WHEN list_sum(p1_payoff) < list_sum(p2_payoff) THEN p1_name
                WHEN list_sum(p2_payoff) < list_sum(p1_payoff) THEN p2_name
                ELSE NULL
            END AS Looser,
            list_sum(p1_payoff) = list_sum(p2_payoff) AS is_draw
        FROM sample_second
        UNION ALL
        SELECT 
            p1_name,
            p2_name,
            list_sum(p1_payoff) AS p1_points,
            list_sum(p2_payoff) AS p2_points,
            CASE 
                WHEN list_sum(p1_payoff) > list_sum(p2_payoff) THEN p1_name
                WHEN list_sum(p2_payoff) > list_sum(p1_payoff) THEN p2_name
                ELSE NULL
            END AS winner,
            CASE 
                WHEN list_sum(p1_payoff) < list_sum(p2_payoff) THEN p1_name
                WHEN list_sum(p2_payoff) < list_sum(p1_payoff) THEN p2_name
                ELSE NULL
            END AS Looser,
            list_sum(p1_payoff) = list_sum(p2_payoff) AS is_draw
        FROM sample_third
    )
    WHERE Winner = '{player}'
    GROUP BY Looser, Winner
    ORDER BY perdidos DESC
    """)

┌────────────────────────┬─────────────────┬──────────┐
│         Looser         │     winner      │ perdidos │
│        varchar         │     varchar     │  int64   │
├────────────────────────┼─────────────────┼──────────┤
│ BinarySunset           │ Adaptive Pavlov │       20 │
│ Permissive Tit for Tat │ Adaptive Pavlov │       12 │
│ Uniform Random         │ Adaptive Pavlov │       11 │
│ Contrite TFT           │ Adaptive Pavlov │       10 │
│ Generous TFT           │ Adaptive Pavlov │        6 │
│ Always 0               │ Adaptive Pavlov │        2 │
│ Castigador Infernal    │ Adaptive Pavlov │        1 │
└────────────────────────┴─────────────────┴──────────┘

### Empates

In [58]:
duckdb.query(f"""
        SELECT  p1_name, p2_name, list_sum(p1_payoff) AS p1_points, list_sum(p2_payoff) AS p2_points,  list_sum(p1_payoff) = list_sum(p2_payoff) AS is_draw
        FROM sample_first
        WHERE is_draw = true
    """)

┌────────────────────┬────────────────────────────┬───────────┬───────────┬─────────┐
│      p1_name       │          p2_name           │ p1_points │ p2_points │ is_draw │
│      varchar       │          varchar           │  int128   │  int128   │ boolean │
├────────────────────┼────────────────────────────┼───────────┼───────────┼─────────┤
│ Adaptive Pavlov    │ Agente Astuto              │         2 │         2 │ true    │
│ Adaptive Pavlov    │ BinarySunset               │         0 │         0 │ true    │
│ Adaptive Pavlov    │ CopyCat                    │        63 │        63 │ true    │
│ Adaptive Pavlov    │ Deterministic Simpletron   │        80 │        80 │ true    │
│ Adaptive Pavlov    │ Deterministic Simpletron   │        36 │        36 │ true    │
│ Adaptive Pavlov    │ Generous TFT               │        28 │        28 │ true    │
│ Adaptive Pavlov    │ Weighted Random 2, 3, or 4 │         8 │         8 │ true    │
│ Agente Astuto      │ Deterministic Simpletron   │        11 │        11 │ true    │
│ Agente Astuto      │ Grim Trigger               │        12 │        12 │ true    │
│ BinarySunset       │ Contrite TFT               │         0 │         0 │ true    │
│      ·             │  ·                         │         · │         · │  ·      │
│      ·             │  ·                         │         · │         · │  ·      │
│      ·             │  ·                         │         · │         · │  ·      │
│ Contrite TFT       │ WSLS                       │         5 │         5 │ true    │
│ CopyCat            │ Generous TFT               │        36 │        36 │ true    │
│ CopyCat            │ Permissive Tit for Tat     │       392 │       392 │ true    │
│ CopyCat            │ Random 2 or 3              │       114 │       114 │ true    │
│ CopyCat            │ Weighted Random 2, 3, or 4 │       291 │       291 │ true    │
│ CopyCat            │ Weighted Random 2, 3, or 4 │        30 │        30 │ true    │
│ CopyCat            │ WSLS                       │       174 │       174 │ true    │
│ Detective Avanzado │ Permissive Tit for Tat     │        11 │        11 │ true    │
│ Detective Avanzado │ Permissive Tit for Tat     │        11 │        11 │ true    │
│ Random 2 or 3      │ WSLS                       │        33 │        33 │ true    │
├────────────────────┴────────────────────────────┴───────────┴───────────┴─────────┤
│ 27 rows (20 shown)                                                      5 columns │
└───────────────────────────────────────────────────────────────────────────────────┘

In [66]:
duckdb.query(f"""
        SELECT player_name , count() as empates
        FROM (
            SELECT  p1_name as player_name, list_sum(p1_payoff) AS p1_points, list_sum(p2_payoff) AS p2_points,  list_sum(p1_payoff) = list_sum(p2_payoff) AS is_draw
            FROM sample_first
            WHERE is_draw = true
            UNION ALL 
            SELECT  p2_name as player_name, list_sum(p1_payoff) AS p1_points, list_sum(p2_payoff) AS p2_points,  list_sum(p1_payoff) = list_sum(p2_payoff) AS is_draw
            FROM sample_first
            WHERE is_draw = true
            UNION ALL
            SELECT  p1_name as player_name, list_sum(p1_payoff) AS p1_points, list_sum(p2_payoff) AS p2_points,  list_sum(p1_payoff) = list_sum(p2_payoff) AS is_draw
            FROM sample_second
            WHERE is_draw = true
            UNION ALL 
            SELECT  p2_name as player_name, list_sum(p1_payoff) AS p1_points, list_sum(p2_payoff) AS p2_points,  list_sum(p1_payoff) = list_sum(p2_payoff) AS is_draw
            FROM sample_second
            WHERE is_draw = true
            UNION ALL
            SELECT  p1_name as player_name, list_sum(p1_payoff) AS p1_points, list_sum(p2_payoff) AS p2_points,  list_sum(p1_payoff) = list_sum(p2_payoff) AS is_draw
            FROM sample_third
            WHERE is_draw = true
            UNION ALL 
            SELECT  p2_name as player_name, list_sum(p1_payoff) AS p1_points, list_sum(p2_payoff) AS p2_points,  list_sum(p1_payoff) = list_sum(p2_payoff) AS is_draw
            FROM sample_third
            WHERE is_draw = true
        )
        GROUP BY player_name
        ORDER BY empates DESC
    """)

┌────────────────────────────┬─────────┐
│        player_name         │ empates │
│          varchar           │  int64  │
├────────────────────────────┼─────────┤
│ CopyCat                    │     230 │
│ Generous TFT               │     136 │
│ Contrite TFT               │     126 │
│ Tit for Tat                │     123 │
│ Permissive Tit for Tat     │     121 │
│ BinarySunset               │     105 │
│ Agente Astuto              │      92 │
│ Adaptive Pavlov            │      86 │
│ Deterministic Simpletron   │      82 │
│ Weighted Random 2, 3, or 4 │      60 │
│ WSLS                       │      42 │
│ Random 2 or 3              │      42 │
│ Castigador Infernal        │      34 │
│ Hat Tricker                │      28 │
│ Grim Trigger               │      28 │
│ Detective Avanzado         │      26 │
│ Focal 5                    │      23 │
│ Always 3                   │      19 │
│ Uniform Random             │       5 │
├────────────────────────────┴─────────┤
│ 19 rows                    2 columns │
└──────────────────────────────────────┘

## Evolution

In [70]:
duckdb.query(f"""
        SELECT *
        FROM sample_second
    """).pl()

shape: (1_638, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ game_numb ┆ repetitio ┆ num_round ┆ p1_name   ┆ … ┆ p2_payoff ┆ mean_scor ┆ mean_scor ┆ generati │
│ er        ┆ n         ┆ s         ┆ ---       ┆   ┆ ---       ┆ e_p1      ┆ e_p2      ┆ on       │
│ ---       ┆ ---       ┆ ---       ┆ str       ┆   ┆ list[i64] ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ i64       ┆ i64       ┆           ┆   ┆           ┆ f64       ┆ f64       ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 1         ┆ 6         ┆ Adaptive  ┆ … ┆ [2, 3, …  ┆ 2.0       ┆ 2.5       ┆ 1        │
│           ┆           ┆           ┆ Pavlov    ┆   ┆ 3]        ┆           ┆           ┆          │
│ 2         ┆ 2         ┆ 111       ┆ Adaptive  ┆ … ┆ [2, 3, …  ┆ 1.981982  ┆ 2.153153  ┆ 1        │
│           ┆           ┆           ┆ Pavlov    ┆   ┆ 3]        ┆           ┆           ┆          │
│ 3         ┆ 1         ┆ 5         ┆ Adaptive  ┆ … ┆ [0, 0, …  ┆ 0.0       ┆ 0.0       ┆ 1        │
│           ┆           ┆           ┆ Pavlov    ┆   ┆ 0]        ┆           ┆           ┆          │
│ 4         ┆ 2         ┆ 23        ┆ Adaptive  ┆ … ┆ [0, 0, …  ┆ 0.130435  ┆ 0.086957  ┆ 1        │
│           ┆           ┆           ┆ Pavlov    ┆   ┆ 0]        ┆           ┆           ┆          │
│ 5         ┆ 1         ┆ 97        ┆ Adaptive  ┆ … ┆ [2, 2, …  ┆ 1.989691  ┆ 1.989691  ┆ 1        │
│           ┆           ┆           ┆ Pavlov    ┆   ┆ 2]        ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 152       ┆ 2         ┆ 4         ┆ Random 2  ┆ … ┆ [2, 3, …  ┆ 2.25      ┆ 2.5       ┆ 10       │
│           ┆           ┆           ┆ or 3      ┆   ┆ 3]        ┆           ┆           ┆          │
│ 153       ┆ 1         ┆ 83        ┆ Random 2  ┆ … ┆ [2, 0, …  ┆ 1.566265  ┆ 1.783133  ┆ 10       │
│           ┆           ┆           ┆ or 3      ┆   ┆ 3]        ┆           ┆           ┆          │
│ 154       ┆ 2         ┆ 146       ┆ Random 2  ┆ … ┆ [2, 0, …  ┆ 1.40411   ┆ 1.60274   ┆ 10       │
│           ┆           ┆           ┆ or 3      ┆   ┆ 0]        ┆           ┆           ┆          │
│ 155       ┆ 1         ┆ 56        ┆ Weighted  ┆ … ┆ [2, 3, …  ┆ 1.535714  ┆ 1.892857  ┆ 10       │
│           ┆           ┆           ┆ Random 2, ┆   ┆ 2]        ┆           ┆           ┆          │
│           ┆           ┆           ┆ 3, or 4   ┆   ┆           ┆           ┆           ┆          │
│ 156       ┆ 2         ┆ 1         ┆ Weighted  ┆ … ┆ [2]       ┆ 2.0       ┆ 2.0       ┆ 10       │
│           ┆           ┆           ┆ Random 2, ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 3, or 4   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [81]:
duckdb.query(f"""
        SELECT DISTINCT(p1_name, p2_name)
        FROM sample_second
        WHERE repetition = 1 and generation = 1
    """).pl()

shape: (91, 1)
┌─────────────────────────────────┐
│ main."row"(p1_name, p2_name)    │
│ ---                             │
│ struct[2]                       │
╞═════════════════════════════════╡
│ {"Adaptive Pavlov","CopyCat"}   │
│ {"BinarySunset","Grim Trigger"… │
│ {"BinarySunset","Random 2 or 3… │
│ {"Hat Tricker","Permissive Tit… │
│ {"Adaptive Pavlov","Agente Ast… │
│ …                               │
│ {"Random 2 or 3","Weighted Ran… │
│ {"Adaptive Pavlov","Detective … │
│ {"Adaptive Pavlov","Weighted R… │
│ {"Contrite TFT","Generous TFT"… │
│ {"Contrite TFT","WSLS"}         │
└─────────────────────────────────┘

# Global

In [10]:
dataframes = []
for file in files:
    match = regex.match(file)
    if match:
        edition = match.group(1)
        phase = match.group(2)
        var_name = f"df_{edition}_{phase}"
        dataframes.append(var_name)
        globals()[var_name] = pl.read_parquet(f'{path}{file}')

# Acceso:
df_20251207_110916_first_phase  # variable creada dinámicamente

shape: (182, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ game_numb ┆ repetitio ┆ num_round ┆ p1_name   ┆ … ┆ p1_payoff ┆ p2_payoff ┆ mean_scor ┆ mean_sco │
│ er        ┆ n         ┆ s         ┆ ---       ┆   ┆ ---       ┆ ---       ┆ e_p1      ┆ re_p2    │
│ ---       ┆ ---       ┆ ---       ┆ str       ┆   ┆ list[i64] ┆ list[i64] ┆ ---       ┆ ---      │
│ i64       ┆ i64       ┆ i64       ┆           ┆   ┆           ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 1         ┆ 1         ┆ Adaptive  ┆ … ┆ [2]       ┆ [2]       ┆ 2.0       ┆ 2.0      │
│           ┆           ┆           ┆ Pavlov    ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2         ┆ 35        ┆ Adaptive  ┆ … ┆ [2, 2, …  ┆ [2, 2, …  ┆ 1.971429  ┆ 2.142857 │
│           ┆           ┆           ┆ Pavlov    ┆   ┆ 2]        ┆ 2]        ┆           ┆          │
│ 3         ┆ 1         ┆ 100       ┆ Adaptive  ┆ … ┆ [0, 0, …  ┆ [0, 0, …  ┆ 1.62      ┆ 1.29     │
│           ┆           ┆           ┆ Pavlov    ┆   ┆ 3]        ┆ 2]        ┆           ┆          │
│ 4         ┆ 2         ┆ 10        ┆ Adaptive  ┆ … ┆ [0, 0, …  ┆ [0, 0, …  ┆ 0.0       ┆ 0.0      │
│           ┆           ┆           ┆ Pavlov    ┆   ┆ 0]        ┆ 0]        ┆           ┆          │
│ 5         ┆ 1         ┆ 49        ┆ Adaptive  ┆ … ┆ [2, 2, …  ┆ [2, 2, …  ┆ 2.0       ┆ 2.020408 │
│           ┆           ┆           ┆ Pavlov    ┆   ┆ 2]        ┆ 2]        ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 178       ┆ 2         ┆ 49        ┆ Random 2  ┆ … ┆ [2, 3, …  ┆ [3, 2, …  ┆ 1.857143  ┆ 1.755102 │
│           ┆           ┆           ┆ or 3      ┆   ┆ 3]        ┆ 2]        ┆           ┆          │
│ 179       ┆ 1         ┆ 22        ┆ Random 2  ┆ … ┆ [3, 0, …  ┆ [2, 0, …  ┆ 1.5       ┆ 1.5      │
│           ┆           ┆           ┆ or 3      ┆   ┆ 2]        ┆ 3]        ┆           ┆          │
│ 180       ┆ 2         ┆ 48        ┆ Random 2  ┆ … ┆ [3, 0, …  ┆ [2, 0, …  ┆ 1.5       ┆ 1.75     │
│           ┆           ┆           ┆ or 3      ┆   ┆ 0]        ┆ 0]        ┆           ┆          │
│ 181       ┆ 1         ┆ 35        ┆ Weighted  ┆ … ┆ [2, 2, …  ┆ [2, 3, …  ┆ 1.857143  ┆ 2.628571 │
│           ┆           ┆           ┆ Random 2, ┆   ┆ 2]        ┆ 2]        ┆           ┆          │
│           ┆           ┆           ┆ 3, or 4   ┆   ┆           ┆           ┆           ┆          │
│ 182       ┆ 2         ┆ 30        ┆ Weighted  ┆ … ┆ [3, 2, …  ┆ [2, 3, …  ┆ 1.7       ┆ 2.166667 │
│           ┆           ┆           ┆ Random 2, ┆   ┆ 2]        ┆ 3]        ┆           ┆          │
│           ┆           ┆           ┆ 3, or 4   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [13]:
super_query_elements = []
for dataframe_name in dataframes:
    super_query_elements.append(f"""
    SELECT p1_name as player_name, list_sum(p1_payoff) as player_score, num_rounds
    FROM {dataframe_name}
    UNION ALL
    SELECT p2_name as player_name, list_sum(p2_payoff) as player_score, num_rounds
    FROM {dataframe_name}
    """
    )
super_query = "\nUNION ALL\n".join(super_query_elements)

In [15]:
# Total
duckdb.query(f"""
SELECT player_name, SUM(player_score) as total_score, SUM(num_rounds) as total_rounds, total_score/total_rounds as Average
FROM (
    {super_query}
    )
GROUP BY player_name
ORDER BY Average DESC
""")

┌────────────────────────────┬─────────────┬──────────────┬───────────────────────┐
│        player_name         │ total_score │ total_rounds │        Average        │
│          varchar           │   int128    │    int128    │        double         │
├────────────────────────────┼─────────────┼──────────────┼───────────────────────┤
│ Adaptive Pavlov            │      857785 │       438358 │    1.9568138370920571 │
│ Focal 5                    │      470502 │       245677 │     1.915124329912853 │
│ Castigador Infernal        │      453862 │       241113 │     1.882362211908939 │
│ Hat Tricker                │      825744 │       450168 │     1.834301860638695 │
│ Weighted Random 2, 3, or 4 │      805074 │       445026 │    1.8090493589138612 │
│ Contrite TFT               │      723097 │       434906 │    1.6626512395782076 │
│ Random 2 or 3              │      736384 │       443828 │    1.6591652622186974 │
│ WSLS                       │      719322 │       437877 │    1.6427489911550504 │
│ Generous TFT               │      665606 │       433525 │    1.5353347557810968 │
│ Permissive Tit for Tat     │      663498 │       442922 │     1.498001905527384 │
│ Agente Astuto              │      662933 │       446900 │    1.4834034459610652 │
│ Tit for Tat                │      359973 │       249531 │    1.4425983144378856 │
│ CopyCat                    │      630562 │       437374 │    1.4416997809654895 │
│ BinarySunset               │      592161 │       412240 │    1.4364472152144383 │
│ Deterministic Simpletron   │      595484 │       440787 │    1.3509563576058277 │
│ Always 3                   │      319190 │       249103 │     1.281357510748566 │
│ Grim Trigger               │      549442 │       438365 │    1.2533892988719446 │
│ Detective Avanzado         │      533945 │       436212 │    1.2240493154704593 │
│ Uniform Random             │      122799 │       157312 │    0.7806079637917006 │
│ Always 0                   │         160 │        25780 │ 0.0062063615205585725 │
├────────────────────────────┴─────────────┴──────────────┴───────────────────────┤
│ 20 rows                                                               4 columns │
└─────────────────────────────────────────────────────────────────────────────────┘